-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 09:08:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_banco_malvader
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_banco_malvader
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_banco_malvader` DEFAULT CHARACTER SET utf8 ;
USE `db_banco_malvader` ;

-- -----------------------------------------------------
-- Table `db_banco_malvader`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` DATE,
  `telefone` VARCHAR(15) NOT NULL,
  `tipo_usuario` ENUM('FUNCIONARIO', 'CLIENTE') NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;

-- drop schema db_banco_malvader;

-- -----------------------------------------------------
-- Table `db_banco_malvader`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `codigo_funcionario` VARCHAR(20) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_funcionario`),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `db_banco_malvader`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_usuario_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `db_banco_malvader`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `local` VARCHAR(100) NOT NULL,
  `numero_casa` INT NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `db_banco_malvader`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`conta` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `numero_conta` VARCHAR(20) NOT NULL,
  `agencia` VARCHAR(10) NOT NULL,
  `saldo` DECIMAL(15,2) NOT NULL,
  `tipo_conta` ENUM('POUPANCA', 'CORRENTE') NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_conta`),
  INDEX `fk_conta_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_conta_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `db_banco_malvader`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`conta_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`conta_corrente` (
  `id_conta_corrente` INT NOT NULL AUTO_INCREMENT,
  `limite` DECIMAL(15,2) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `conta_id_conta` INT NOT NULL,
  PRIMARY KEY (`id_conta_corrente`),
  INDEX `fk_conta_corrente_conta1_idx` (`conta_id_conta` ASC) VISIBLE,
  CONSTRAINT `fk_conta_corrente_conta1`
    FOREIGN KEY (`conta_id_conta`)
    REFERENCES `db_banco_malvader`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`conta_poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`conta_poupanca` (
  `id_conta_poupanca` INT NOT NULL AUTO_INCREMENT,
  `taxa_redimento` DECIMAL(5,2) NOT NULL,
  `conta_id_conta` INT NOT NULL,
  PRIMARY KEY (`id_conta_poupanca`),
  INDEX `fk_conta_poupanca_conta1_idx` (`conta_id_conta` ASC) VISIBLE,
  CONSTRAINT `fk_conta_poupanca_conta1`
    FOREIGN KEY (`conta_id_conta`)
    REFERENCES `db_banco_malvader`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`transacao` (
  `id_transacao` INT NOT NULL AUTO_INCREMENT,
  `tipo_transacao` ENUM('DEPOSITO', 'SAQUE', 'TRANSFERENCIA') NOT NULL,
  `valor` DECIMAL(15,2) NOT NULL,
  `data_hora` TIMESTAMP NOT NULL,
  `conta_id_conta` INT NOT NULL,
  PRIMARY KEY (`id_transacao`),
  INDEX `fk_transacao_conta1_idx` (`conta_id_conta` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_conta1`
    FOREIGN KEY (`conta_id_conta`)
    REFERENCES `db_banco_malvader`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_banco_malvader`.`relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_banco_malvader`.`relatorio` (
  `id_relatorio` INT NOT NULL AUTO_INCREMENT,
  `tipo_relatorio` VARCHAR(50) NOT NULL,
  `data_geracao` TIMESTAMP NOT NULL,
  `conteudo` TEXT(100) NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  PRIMARY KEY (`id_relatorio`),
  INDEX `fk_relatorio_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_relatorio_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `db_banco_malvader`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
